/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 eth.gltf --transform
Author: ÆON (https://sketchfab.com/xaeon)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ethereum-a158be5de8d9467da798fcbc4894aa72
Title: Ethereum
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/eth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cone001_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={1.3} position={[0, -2, 0]}/>
    </group>
  )
}

useGLTF.preload('/eth-transformed.glb')
