/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 gitlogo.gltf --transform
Author: pissang (https://sketchfab.com/YiChen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/github-octocat-c8a4795ce3fe4b21a4c40895cb9cb6a5
Title: GitHub Octocat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gitlogo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0}  position={[-2.00, 2., 0.6]} scale={0.015} />  {/* balckbody */}
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_1}  position={[-2.00, 2, 0.8]} scale={0.015} /> {/* faceskin */}
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_2}  position={[-2.00, 2., 0.9]} scale={0.015} />  {/* white part eyes */}
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_3}  position={[-2.00, 2, 0.95]} scale={0.015} />       {/* brown part eyes */}
      {/* <mesh geometry={nodes.Object_16.geometry} material={materials.material_6}  position={[-2, 9, -8.325]} scale={0.015} />    chain */}
    </group>
  )
}

useGLTF.preload('/gitlogo-transformed.glb')
