/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 google.gltf --transform
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/google-logo-7e904bea654b40d7861c84a7cb5cc969
Title: Google Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/google-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Google_Logo_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[2.386, 0.182, -15.929]} />
    </group>
  )
}

useGLTF.preload('/google-transformed.glb')
